version: '3.8'
services:
  benchmark_postgres: # Service name
    image: postgres:16
    container_name: benchmark_postgres # Fixed name for Python to find
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    shm_size: 2gb
    volumes:
      # NAMED VOLUME (Docker manages this. You don't touch it.)
      # This is where your ingested data will live.
      - pg_bench_data:/var/lib/postgresql/data

  benchmark_actian:
    image: actian/vector-ce:latest
    container_name: benchmark_actian
    ports:
      - "27832:27832" # Net/ODBC Port
      - "27839:27839" # JDBC Port
    environment:
      - AV_PASSWORD=password
    volumes:
      - actian_bench_data:/home/actian/data

# Declare the volume here so Docker knows to create it
volumes:
  pg_bench_data:
  actian_bench_data: