[project]
name = "sql_benchmarks"
version = "0.1.0"
description = "SQL Benchmarks V7 Platform"
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "dagster",
    "dagster-cloud",
    "dagster-postgres",
    "dagster-duckdb",
    "pandas",
    "plotly",
    "polars",
    "pyarrow",
    "psycopg2-binary",
    "sqlalchemy",
    "psutil",
    "pyyaml",
    "numpy",
    "paramiko>=3.0.0",
    "sshtunnel>=0.4.0",
    "scp>=0.14.0",
]

[project.optional-dependencies]
dev = [
    "dagster-webserver", 
    "pytest"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "sql_benchmarks.definitions"
code_location_name = "sql_benchmarks"

[tool.setuptools.packages.find]
exclude = ["sql_benchmarks_tests"]
